### ISSUE TITLE
operand.namespace should be dropped

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#114]
**What happened**:

I create nfd CR:

```
kubectl apply -f - << EOF
apiVersion: nfd.kubernetes.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-master-server
  namespace: operators
spec:
  operand:
    image: 'k8s.gcr.io/nfd/node-feature-discovery:v0.10.1'
    namespace: nfd
EOF
```

NFD get's deployed in operators namespace, as it should. The `operand.namespace` field has no effect (as it shouldn't as it shouldn't be allowed to "contaminate" arbitrary namespaces with NFD) and it should be dropped from the CRD.

**What you expected to happen**:

The `operand.namespace` parameter should not be accepted at al.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:
